name: run-verilog-tests
on:
  - push
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: 'pip install --user .'
      - run: 'sudo apt-get install -y make iverilog'
      - run: 'make -C verilog test'
